name: CD Pipeline

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: [CI Pipeline]
    types: [completed]

permissions:
  contents: read
  deployments: write
  id-token: write

jobs:
  deploy:
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'workflow_run' &&
       github.event.workflow_run.conclusion == 'success' &&
       github.event.workflow_run.head_branch == github.event.repository.default_branch)
    runs-on: ubuntu-latest
    environment: production
    concurrency: smart-ai-meal-planner
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP_NAME: smart-ai-meal-planner
      HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
    defaults:
      run:
        working-directory: ./smart_meal_planner_backend
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: 'pip'
          cache-dependency-path: '**/requirements.txt'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ env.HEROKU_API_KEY }}
          heroku_app_name: ${{ env.HEROKU_APP_NAME }}
          heroku_email: ${{ env.HEROKU_EMAIL }}
          usedocker: true
          appdir: "smart_meal_planner_backend"
          docker_heroku_process_type: "web"