name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://smart-ai-meal-planner-5e9f02da078d.herokuapp.com
    steps:
      - uses: actions/checkout@v2
      
      - name: Verify Heroku Stack
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku stack -a smart-ai-meal-planner
      
      - name: Build and push
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "smart-ai-meal-planner"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true
          appdir: "smart_meal_planner_backend"
          docker_heroku_process_type: "web"